<#
.SYNOPSIS
    Attaches a file to an Azure DevOps work item.

.DESCRIPTION
    This script uploads a file as an attachment to a specified Azure DevOps work item
    using the Azure DevOps REST API. The Personal Access Token can be provided via
    parameter, environment variable, or Windows Credential Manager.

.PARAMETER PersonalAccessToken
    Azure DevOps Personal Access Token with Work Items permissions.
    If not provided, will check environment variable AZURE_DEVOPS_PAT or Credential Manager.

.PARAMETER WorkItemId
    The ID of the work item to attach the file to.

.PARAMETER FilePath
    The full path to the file to be attached.

.EXAMPLE
    .\Attach-FileToWorkItem.ps1 -WorkItemId "834687" -FilePath "C:\path\to\file.md"

.EXAMPLE
    .\Attach-FileToWorkItem.ps1 -PersonalAccessToken "abc123..." -WorkItemId "834687" -FilePath "C:\path\to\file.md"

.NOTES
    Author: Generated by GitHub Copilot
    Requires: PowerShell 5.1 or later
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory = $false, HelpMessage = "Azure DevOps Personal Access Token")]
    [string]$PersonalAccessToken,

    [Parameter(Mandatory = $true, HelpMessage = "Work item ID to attach file to")]
    [ValidateNotNullOrEmpty()]
    [string]$WorkItemId,

    [Parameter(Mandatory = $true, HelpMessage = "Path to the file to attach")]
    [ValidateNotNullOrEmpty()]
    [string]$FilePath
)

# Function to get PAT securely
function Get-PersonalAccessToken {
    # 1. Check if provided as parameter
    if ($PersonalAccessToken) {
        Write-Verbose "Using PAT provided as parameter"
        return $PersonalAccessToken
    }

    # 2. Check environment variable
    if ($env:AZURE_DEVOPS_PAT) {
        Write-Verbose "Using PAT from environment variable AZURE_DEVOPS_PAT"
        return $env:AZURE_DEVOPS_PAT
    }

    # 3. Check Windows Credential Manager
    try {
        $credential = Get-StoredCredential -Target "AzureDevOps_PAT" -ErrorAction Stop
        if ($credential) {
            Write-Verbose "Using PAT from Windows Credential Manager"
            return $credential.GetNetworkCredential().Password
        }
    } catch {
        Write-Verbose "Credential Manager not available or credential not found"
    }

    # 4. Prompt user securely
    Write-Host "Personal Access Token not found. Please enter it securely:" -ForegroundColor Yellow
    $secureToken = Read-Host -AsSecureString "Enter Azure DevOps Personal Access Token"
    return [Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($secureToken))
}

# Configuration
$azureDevOpsOrgUrl = "https://ecolaboip.visualstudio.com"
$azureDevOpsProject = "Dynamics 365 Convergence"
$apiVersion = "7.1-preview.3"

# Get PAT securely
$pat = Get-PersonalAccessToken
if (-not $pat) {
    throw "No Personal Access Token provided or found. Use -PersonalAccessToken parameter, set AZURE_DEVOPS_PAT environment variable, or store in Windows Credential Manager."
}

# Validate file exists
if (-not (Test-Path $FilePath)) {
    throw "File not found: $FilePath"
}

# Get file information
$fileInfo = Get-Item $FilePath
$fileName = $fileInfo.Name
$fileSize = $fileInfo.Length

Write-Verbose "Processing file: $fileName ($fileSize bytes)"

# Create authorization header
$authHeader = @{
    "Authorization" = "Basic " + [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes(":$pat"))
}

# Upload headers for file upload
$uploadHeaders = $authHeader.Clone()
$uploadHeaders["Content-Type"] = "application/octet-stream"

try {
    Write-Host "Uploading file '$fileName' to work item $WorkItemId..."

    # Step 1: Upload the file as an attachment
    $uploadUrl = "$azureDevOpsOrgUrl/$azureDevOpsProject/_apis/wit/attachments?fileName=$fileName&api-version=$apiVersion"

    Write-Verbose "Upload URL: $uploadUrl"

    $fileContent = [System.IO.File]::ReadAllBytes($FilePath)
    $uploadResponse = Invoke-RestMethod -Uri $uploadUrl -Method Post -Headers $uploadHeaders -Body $fileContent

    Write-Verbose "File uploaded successfully. Attachment URL: $($uploadResponse.url)"

    # Step 2: Attach the uploaded file to the work item
    $attachmentUrl = $uploadResponse.url

    $attachBody = @"
[
  {
    "op": "add",
    "path": "/relations/-",
    "value": {
      "rel": "AttachedFile",
      "url": "$attachmentUrl",
      "attributes": {
        "name": "$fileName"
      }
    }
  }
]
"@

    $updateUrl = "$azureDevOpsOrgUrl/$azureDevOpsProject/_apis/wit/workitems/$WorkItemId/?api-version=$apiVersion"

    Write-Verbose "Update URL: $updateUrl"

    $updateHeaders = $authHeader.Clone()
    $updateHeaders["Content-Type"] = "application/json-patch+json"

    $updateResponse = Invoke-RestMethod -Uri $updateUrl -Method Patch -Headers $updateHeaders -Body $attachBody

    Write-Host "✅ File '$fileName' attached successfully to work item $WorkItemId"

} catch {
    Write-Error "Failed to attach file: $($_.Exception.Message)"
    exit 1
}
